import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 980 } });
const ready = () => p.waitForFunction(() => document.querySelector('#canvas').dataset.surface !== 'loading');
await p.goto('http://localhost:5175/documents'); await ready();
await p.click('[data-testid="open-tray"]'); await p.waitForSelector('[data-testid="tray-table"]');
await p.screenshot({ path: '/tmp/sh-tray.png' });
await p.keyboard.press('Escape');
await p.click('[data-testid="open-presets"]'); await p.waitForSelector('[data-testid="preset-option"]');
await p.screenshot({ path: '/tmp/sh-presets.png' });
await p.keyboard.press('Escape');
await p.click('#open-shortcuts'); await p.waitForSelector('[data-binding="upload-submit"]');
await p.screenshot({ path: '/tmp/sh-shortcuts.png' });
await p.keyboard.press('Escape');
await p.goto('http://localhost:5175/documents/transfers'); await ready();
await p.screenshot({ path: '/tmp/sh-transfers.png' });
await p.goto('http://localhost:5175/developer/console'); await ready();
await p.click('[data-testid="console-run"]');
await p.waitForSelector('[data-console-state="complete"]');
await p.screenshot({ path: '/tmp/sh-run.png' });
await p.goto('http://localhost:5175/settings'); await ready();
await p.click('[data-testid="tab-content-types"]'); await p.waitForSelector('[data-testid="allowed-mime"]');
await p.screenshot({ path: '/tmp/sh-content.png' });
await p.goto('http://localhost:5175/developer/components'); await ready();
await p.screenshot({ path: '/tmp/sh-components.png', fullPage: true });
await p.goto('http://localhost:5175/developer/behavior'); await ready();
await p.screenshot({ path: '/tmp/sh-behavior.png' });
await b.close();
