'use strict';
/**
 * Meridian content model.
 *
 * The corpus in data.json is the single source of truth. Nothing here invents a
 * value: every projection below is a *narrowing* of a corpus record into the
 * shape one surface of the product is allowed to serve.
 *
 * Field governance in this product:
 *   - runtime (duration)  -> authoring-layer private; exists only as a body token
 *   - source commit       -> abbreviated on screen, full only in the publish bundle
 *   - classification      -> lives in the Taxonomy manager, never on the entry
 *   - workflow stage      -> lives in the Delivery Console, never on the entry
 */
const fs = require('fs');
const path = require('path');

const CORPUS = JSON.parse(fs.readFileSync(path.join(__dirname, 'data.json'), 'utf8'));

/* ------------------------------------------------------------------ *
 * deterministic helpers                                              *
 * ------------------------------------------------------------------ */

// seed 101, per fsm meta. Used only for chrome (media library, inbox, ...).
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const slugify = (s) =>
  String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const cap = (s) => String(s).charAt(0).toUpperCase() + String(s).slice(1);

/* ------------------------------------------------------------------ *
 * entry projections                                                  *
 * ------------------------------------------------------------------ */

const reference = (r) => `BR-${r.build_id}`;
const title = (r) => `${cap(r.commit_message)} — ${r.test_suite} pipeline`;
const entrySlug = (r) => `${slugify(r.commit_message)}-${r.build_id}`;
const shortSha = (r) => r.commit_sha.slice(0, 7);

// Publication flag: whether the entry is live on the site. Editorial state,
// deterministic, and independent of the pipeline's own outcome.
const isPublished = (r) => (r.build_id * 7 + r.queue_wait_sec) % 5 !== 0;

const modifiedAt = (r) => r.started_at;
const createdAt = (r) => {
  const t = new Date(r.started_at).getTime() - (r.queue_wait_sec + 90) * 1000;
  return new Date(t).toISOString().replace(/\.\d{3}Z$/, 'Z');
};

/** Every corpus record, in corpus order, with its stable identity fields. */
const ENTRIES = CORPUS.map((r, i) => ({
  index: i,
  record: r,
  reference: reference(r),
  slug: entrySlug(r),
  title: title(r),
  author: r.triggered_by,
  created: createdAt(r),
  modified: modifiedAt(r),
  published: isPublished(r),
}));

const BY_REFERENCE = new Map(ENTRIES.map((e) => [e.reference, e]));

/* -- collection row: reference, title, author, modified, published -- */
function collectionRow(e) {
  return {
    reference: e.reference,
    title: e.title,
    author: e.author,
    modified: e.modified,
    published: e.published,
  };
}

/* -- editor payload: authoring fields + unresolved body ------------- */
const BODY_TEMPLATE = [
  '## Summary',
  '',
  'The `{{ build.suite }}` suite executed for entry `{{ entry.reference }}` on runner',
  '`{{ build.runner }}`. This report is generated by the status-site publisher and is',
  'reviewed by the on-call editor before it goes live.',
  '',
  '## Timing',
  '',
  'Elapsed wall-clock time: **{{ build.duration_sec }}** seconds.',
  '',
  'The job sat {{ build.queue_wait_sec }} seconds in the queue before a runner picked',
  'it up.',
  '',
  '## Source',
  '',
  'Published from {{ build.commit_short }} — {{ build.commit_message }}.',
].join('\n');

function editorPayload(e) {
  const r = e.record;
  return {
    reference: e.reference,
    slug: e.slug,
    title: e.title,
    collection: 'Build Reports',
    author: e.author,
    created: e.created,
    modified: e.modified,
    published: e.published,
    revision: 3 + (r.build_id % 4),
    locale: 'en-GB',
    // Body ships with its tokens unresolved: the authoring layer never expands
    // them. Rendering for the site is what resolves a token.
    body: BODY_TEMPLATE,
    tokens: [
      { token: '{{ build.suite }}', resolves: 'Test suite label' },
      { token: '{{ entry.reference }}', resolves: 'Entry reference' },
      { token: '{{ build.runner }}', resolves: 'Runner image' },
      { token: '{{ build.duration_sec }}', resolves: 'Elapsed seconds (resolved at render)' },
      { token: '{{ build.queue_wait_sec }}', resolves: 'Queue wait seconds' },
      { token: '{{ build.commit_short }}', resolves: 'Abbreviated source commit' },
      { token: '{{ build.commit_message }}', resolves: 'Commit subject' },
    ],
    // Source chip — abbreviated, as everywhere on screen.
    source: { short: shortSha(r), message: r.commit_message },
    runner: r.runner,
    suite: r.test_suite,
    governance: {
      classification: 'Governed in the Taxonomy manager',
      workflow_stage: 'Governed in the Delivery Console',
    },
    seo: seoPanel(e),
  };
}

/* -- preview payload: resolved body for exactly one entry ----------- */
function previewPayload(e) {
  const r = e.record;
  return {
    reference: e.reference,
    headline: e.title,
    byline: e.author,
    published_at: e.modified,
    locale: 'en-GB',
    sections: [
      {
        heading: 'Summary',
        paragraphs: [
          `The ${r.test_suite} suite executed for entry ${e.reference} on runner ${r.runner}. ` +
            'This report is generated by the status-site publisher and is reviewed by the ' +
            'on-call editor before it goes live.',
        ],
      },
    ],
    // The one resolved runtime sentence. This entry only.
    runtime_sentence: {
      lead: 'Elapsed wall-clock time:',
      value: r.duration_sec,
      unit: 'seconds',
    },
    queue_sentence: `The job sat ${r.queue_wait_sec} seconds in the queue before a runner picked it up.`,
    credit: `Published from ${shortSha(r)} — ${r.commit_message}.`,
  };
}

/* -- publish bundle: frontmatter + unresolved body ------------------ */
function bundleText(e) {
  const r = e.record;
  const fm = [
    '---',
    `title: ${e.title}`,
    `reference: ${e.reference}`,
    `slug: ${e.slug}`,
    'collection: build-reports',
    `author: ${e.author}`,
    `created: ${e.created}`,
    `modified: ${e.modified}`,
    `published: ${e.published}`,
    `locale: en-GB`,
    `source_commit: ${r.commit_sha}`,
    `source_commit_short: ${shortSha(r)}`,
    `runner: ${r.runner}`,
    `suite: ${r.test_suite}`,
    'bundle_format: meridian/publish-bundle@2',
    '---',
    '',
  ].join('\n');
  const note = [
    '<!-- Publish bundle: authoring source only. Derived metrics and relational',
    '     data (elapsed seconds, classification terms, workflow stage) are not',
    '     part of the bundle; body tokens ship unresolved. -->',
    '',
  ].join('\n');
  return fm + note + BODY_TEMPLATE + '\n';
}

function bundleFilename(e) {
  return `${e.slug}.bundle.md`;
}

/* ------------------------------------------------------------------ *
 * taxonomy — classification vocabulary                               *
 * ------------------------------------------------------------------ */

const TERM_BLURB = {
  0: 'Applied by the publisher when an entry is imported. Editors may reassign it, but only in this manager.',
  1: 'Classification is single-select: an entry carries exactly one term from this vocabulary.',
  2: 'Membership is resolved at publish time and is not exposed through the read API.',
  3: 'Entries under this term appear in the weekly digest in the order they were filed.',
  4: 'Renaming this term rewrites the classification on every entry that carries it.',
};

const TERMS = (() => {
  const seen = [];
  for (const e of ENTRIES) {
    const name = e.record.branch;
    let t = seen.find((x) => x.name === name);
    if (!t) {
      t = { name, slug: slugify(name), members: [] };
      seen.push(t);
    }
    t.members.push(e);
  }
  return seen.map((t, i) => ({
    ...t,
    description: TERM_BLURB[i % 5],
    updated: t.members.map((m) => m.modified).sort().slice(-1)[0],
  }));
})();

const TERM_BY_SLUG = new Map(TERMS.map((t) => [t.slug, t]));

/* ------------------------------------------------------------------ *
 * delivery console — workflow stages                                 *
 * ------------------------------------------------------------------ */

const STAGES = (() => {
  const out = [];
  for (const e of ENTRIES) {
    const s = e.record.status;
    let g = out.find((x) => x.id === s);
    if (!g) { g = { id: s, label: cap(s), members: [] }; out.push(g); }
    g.members.push(e);
  }
  return out;
})();

const STAGE_BY_ID = new Map(STAGES.map((s) => [s.id, s]));

/** Public projection served by the read API. Private fields never appear. */
function deliveryRow(e) {
  return { reference: e.reference, slug: e.slug, title: e.title };
}

const DELIVERY_SCHEMA = [
  { field: 'reference', type: 'String', visibility: 'public', queryable: true, note: 'Stable entry key' },
  { field: 'slug', type: 'String', visibility: 'public', queryable: false, note: 'URL segment' },
  { field: 'title', type: 'String', visibility: 'public', queryable: false, note: 'Rendered headline' },
  { field: 'workflow_stage', type: 'Enum', visibility: 'public', queryable: true, note: 'Filter dimension' },
  { field: 'modified', type: 'DateTime', visibility: 'public', queryable: true, note: 'Filter dimension' },
  { field: 'runtime_seconds', type: 'Int', visibility: 'private', queryable: false, note: 'Authoring layer only — omitted from every response' },
  { field: 'source_commit', type: 'String', visibility: 'private', queryable: false, note: 'Authoring layer only — omitted from every response' },
  { field: 'classification', type: 'Reference[]', visibility: 'private', queryable: false, note: 'Resolved at publish time — not a queryable dimension' },
  { field: 'body', type: 'RichText', visibility: 'public', queryable: false, note: 'Not projected in list responses' },
];

/* ------------------------------------------------------------------ *
 * chrome — deterministic filler for the surrounding product          *
 * ------------------------------------------------------------------ */

function seoPanel(e) {
  const rnd = mulberry32(101 + e.record.build_id);
  const score = 58 + Math.floor(rnd() * 40);
  const pool = [
    ['Meta description', 'Meta description is 41 characters; aim for 120–158.'],
    ['Heading order', 'One H2 follows another without intervening prose.'],
    ['Internal links', 'No internal link to the collection index.'],
    ['Alt text', 'Hero image has no alternative text.'],
    ['Canonical', 'Canonical URL inherits the collection default.'],
    ['Reading time', 'Body is shorter than the 300-word site minimum.'],
  ];
  const n = 2 + Math.floor(rnd() * 3);
  return { score, suggestions: pool.slice(0, n).map(([t, d]) => ({ title: t, detail: d })) };
}

const MEDIA = (() => {
  const rnd = mulberry32(101);
  const kinds = ['screenshot', 'diagram', 'chart', 'logo'];
  const names = ['pipeline-graph', 'runner-fleet', 'queue-depth', 'shard-map', 'flake-heatmap',
    'status-banner', 'incident-timeline', 'cache-hit-rate', 'deploy-ring', 'coverage-tree',
    'agent-topology', 'retry-funnel'];
  return names.map((n, i) => ({
    id: `MED-${300 + i}`,
    name: `${n}.png`,
    kind: kinds[i % kinds.length],
    size_kb: 40 + Math.floor(rnd() * 900),
    width: 512 + 96 * (i % 4),
    height: 288 + 72 * (i % 3),
    uploaded_by: ['n.varga', 'p.achebe', 'k.lindqvist', 'r.demir'][i % 4],
    uploaded: `2026-07-${String(2 + ((i * 2) % 26)).padStart(2, '0')}T09:${String(10 + i).padStart(2, '0')}:00Z`,
    used_in: i % 3,
  }));
})();

const LOCALES = [
  { code: 'en-GB', name: 'English (UK)', role: 'source', translated: 100, outdated: 0 },
  { code: 'de-DE', name: 'German', role: 'target', translated: 74, outdated: 6 },
  { code: 'fr-FR', name: 'French', role: 'target', translated: 68, outdated: 11 },
  { code: 'ja-JP', name: 'Japanese', role: 'target', translated: 41, outdated: 3 },
  { code: 'pt-BR', name: 'Portuguese (BR)', role: 'target', translated: 22, outdated: 0 },
];

const INBOX = (() => {
  const rnd = mulberry32(2101);
  const authors = ['n.varga', 'p.achebe', 'k.lindqvist', 'r.demir', 'j.halloran'];
  const bodies = [
    'Can we align the headline casing with the rest of the status site?',
    'The on-call editor asked for a shorter summary here.',
    'Localisation is blocked on this thread — see the German string.',
    'Approved, but please leave the credit line untouched.',
    'This one needs a second reviewer before it goes live.',
    'Reminder: the digest cut-off moved to Thursday 17:00.',
  ];
  return bodies.map((b, i) => ({
    id: `THR-${900 + i}`,
    author: authors[i % authors.length],
    body: b,
    thread: ['Editorial standards', 'Weekly digest', 'Localisation', 'Publishing'][i % 4],
    unread: rnd() > 0.45,
    at: `2026-07-${String(6 + i * 3).padStart(2, '0')}T1${i % 9}:2${i % 9}:00Z`,
  }));
})();

const TRASH = (() => {
  const items = ['Changelog 2.3.9', 'Runbook: cache eviction', 'Post-mortem draft',
    'Status page copy (old)', 'Release note stub', 'Deprecation notice'];
  return items.map((t, i) => ({
    id: `TRS-${77 + i}`,
    title: t,
    collection: ['Changelog', 'Runbooks', 'Post-mortems', 'Site copy'][i % 4],
    deleted_by: ['n.varga', 'j.halloran', 'k.lindqvist'][i % 3],
    deleted: `2026-0${6 + (i % 2)}-${String(4 + i * 3).padStart(2, '0')}T08:30:00Z`,
    purge_in_days: 30 - i * 4,
  }));
})();

const WEBHOOKS = (() => {
  const rnd = mulberry32(777);
  const targets = ['status-site-build', 'search-reindex', 'cdn-purge', 'digest-mailer'];
  return Array.from({ length: 9 }, (_, i) => ({
    id: `WH-${5100 + i}`,
    target: targets[i % targets.length],
    event: i % 3 === 0 ? 'entry.published' : i % 3 === 1 ? 'entry.updated' : 'entry.unpublished',
    code: rnd() > 0.15 ? 200 : 502,
    ms: 40 + Math.floor(rnd() * 420),
    at: `2026-07-28T${String(6 + i).padStart(2, '0')}:${String(11 + i * 3).padStart(2, '0')}:00Z`,
  }));
})();

const API_KEYS = [
  { name: 'status-site (production)', prefix: 'mrd_live_9f2c', scope: 'read', created: '2026-03-02', last_used: '2026-07-28' },
  { name: 'preview renderer', prefix: 'mrd_prev_41ab', scope: 'read', created: '2026-05-19', last_used: '2026-07-27' },
  { name: 'digest mailer', prefix: 'mrd_live_7d10', scope: 'read', created: '2026-06-11', last_used: '2026-07-24' },
];

const CHECKLIST = [
  { label: 'Invite your editorial team', done: true },
  { label: 'Connect a delivery target', done: true },
  { label: 'Define a content model', done: true },
  { label: 'Set up a preview environment', done: false },
  { label: 'Enable scheduled publishing', done: false },
];

const PLUGINS = [
  { name: 'Meridian Insights', blurb: 'Editorial analytics with per-collection funnels.', price: 'from £18/mo' },
  { name: 'Glossary Guard', blurb: 'Terminology linting across every locale.', price: 'free' },
];

/* ------------------------------------------------------------------ *
 * dashboard aggregates (counts of entries — never measures)          *
 * ------------------------------------------------------------------ */

function dashboard() {
  const live = ENTRIES.filter((e) => e.published).length;
  const draft = ENTRIES.length - live;

  const weeks = new Map();
  for (const e of ENTRIES) {
    const d = new Date(e.modified);
    const day = d.getUTCDate();
    const wk = `Jul ${String(1 + Math.floor((day - 1) / 7) * 7).padStart(2, '0')}`;
    weeks.set(wk, (weeks.get(wk) || 0) + 1);
  }
  const velocity = [...weeks.entries()].sort().map(([week, count]) => ({ week, count }));

  const days = new Map();
  for (const e of ENTRIES) days.set(e.modified.slice(0, 10), (days.get(e.modified.slice(0, 10)) || 0) + 1);
  const calendar = [...days.entries()].sort().map(([date, count]) => ({ date, count }));

  // Recently edited: titles only — no reference, no field values.
  const recent = [...ENTRIES].sort((a, b) => (a.modified < b.modified ? 1 : -1))
    .slice(0, 8).map((e) => ({ title: e.title }));

  return {
    collections: [
      { name: 'Build Reports', entries: ENTRIES.length, model: 'build_report' },
      { name: 'Changelog', entries: 26, model: 'changelog_note' },
      { name: 'Runbooks', entries: 14, model: 'runbook' },
      { name: 'Site copy', entries: 9, model: 'fragment' },
    ],
    counts: { live, draft, scheduled: 0, total: ENTRIES.length },
    velocity,
    calendar,
    recent,
    checklist: CHECKLIST,
    plugins: PLUGINS,
    unread: INBOX.filter((t) => t.unread).length,
  };
}

module.exports = {
  ENTRIES, BY_REFERENCE, TERMS, TERM_BY_SLUG, STAGES, STAGE_BY_ID,
  DELIVERY_SCHEMA, MEDIA, LOCALES, INBOX, TRASH, WEBHOOKS, API_KEYS,
  collectionRow, editorPayload, previewPayload, bundleText, bundleFilename,
  deliveryRow, dashboard,
};
